drop table locker_usage_logs;
drop table users;
drop table robots;
drop table locker_queue;
drop table lockers;
drop table access_tokens;
drop table robot_status;
drop table locker_locations;
drop table locker_status;