name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        cd SmartLocker
        mvn -B package --file pom.xml

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # 현재 실행 중인 컨테이너 백업
          cd /home/ubuntu/BackEnd/Docker
          docker-compose ps -q > running_containers.txt
          
          # 새 버전 배포 시도
          sudo docker-compose down
          sudo docker system prune -af
          cd ../SmartLocker
          sudo git pull
          cd ../Docker
          if ! sudo docker-compose up --build -d; then
            # 배포 실패시 이전 버전으로 롤백
            echo "Deployment failed, rolling back..."
            sudo docker-compose up -d $(cat running_containers.txt)
            exit 1
          fi
