name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ main ]

jobs:
  test: # PR 검증용
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and Test
        run: |
          cd SmartLocker
          mvn -B package --file pom.xml
        # 실제 배포는 하지 않고 빌드와 테스트만 수행

  deploy:
    if: github.event_name == 'push'
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        cd SmartLocker
        mvn -B package --file pom.xml

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/BackEnd
          sudo git pull
          cd SmartLocker
          mvn -B package --file pom.xml
          cd ../Docker
          sudo docker-compose down
          sudo docker system prune -af
          sudo docker-compose up --build -d --add-host=host.docker.internal:host-gateway
