name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    if: github.event_name == 'push'
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/BackEnd
          sudo git pull
          cd SmartLocker
          mvn -B package --file pom.xml
          cd ../Docker
          sudo docker-compose down
          sudo docker system prune -af
          sudo docker-compose up --build -d
